In [1]:
pip install faker

Collecting fakerNote: you may need to restart the kernel to use updated packages.

  Downloading Faker-30.8.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\d e l l\appdata\local\programs\python\python310\lib\site-packages (from faker) (2.8.2)
Requirement already satisfied: typing-extensions in c:\users\d e l l\appdata\local\programs\python\python310\lib\site-packages (from faker) (4.4.0)
Requirement already satisfied: six>=1.5 in c:\users\d e l l\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-30.8.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 11.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-30.8.1

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import cx_Oracle
from faker import Faker
import random

# Initialize Faker instance
fake = Faker()


connection = cx_Oracle.connect("system", "Admin@123", "localhost:1521/orcl")
cursor = connection.cursor()

# CREATE (Create a new table)
def create_table():
    try:
        cursor.execute("""
            CREATE TABLE employeees (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(50),
                salary NUMBER(10, 2)
            )
        """)
        print("Table created successfully.")
    except cx_Oracle.DatabaseError as e:
        print(f"Error creating table: {e}")

# INSERT (Insert a new record with Faker-generated data)
def insert_employee(emp_name, emp_salary):
    try:
        cursor.execute("INSERT INTO employeees (name, salary) VALUES (:1, :2)", (emp_name, emp_salary))
        connection.commit()
        print(f"Record inserted: {emp_name}, Salary: {emp_salary}")
    except cx_Oracle.DatabaseError as e:
        print(f"Error inserting data: {e}")

# Use Faker to generate and insert multiple employee records
def insert_fake_employees(num_records):
    for _ in range(num_records):
        emp_name = fake.name()                
        emp_salary = round(random.uniform(30000, 100000), 2)  
        insert_employee(emp_name, emp_salary)

# SELECT (Select records)
def select_employees():
    try:
        cursor.execute("SELECT * FROM employeees")
        rows = cursor.fetchall()
        print("Employee Records:")
        for row in rows:
            print(row)
    except cx_Oracle.DatabaseError as e:
        print(f"Error reading data: {e}")

# UPDATE (Update a record)
def update_employee(emp_id, new_salary):
    try:
        cursor.execute("UPDATE employeees SET salary = :1 WHERE id = :2", (new_salary, emp_id))
        connection.commit()
        print("Record updated successfully.")
    except cx_Oracle.DatabaseError as e:
        print(f"Error updating data: {e}")

# DELETE (Delete a record)
def delete_employee(emp_id):
    try:
        cursor.execute("DELETE FROM employeees WHERE id = :1", (emp_id,))
        connection.commit()
        print("Record deleted successfully.")
    except cx_Oracle.DatabaseError as e:
        print(f"Error deleting data: {e}")

# Main program execution
if __name__ == "__main__":
    # Create table
    create_table()

    # Insert 5 fake employee records
    insert_fake_employees(5)

    # Select records after insertion
    print("After Insertion:")
    select_employees()

    # Update a record
    update_employee(1, 55000)  # Update salary for the employee with id 1

    # Select records again
    print("After Update:")
    select_employees()

    # Delete a record
    delete_employee(2)  # Delete the employee with id 2

    # Select records after deletion
    print("After Deletion:")
    select_employees()

# Close the cursor and connection
cursor.close()
connection.close()

Table created successfully.
Record inserted: Anna Fry, Salary: 69995.45
Record inserted: Rhonda Phillips, Salary: 55199.43
Record inserted: Teresa Sims, Salary: 46893.71
Record inserted: Kaitlin Webb DDS, Salary: 85124.56
Record inserted: Brian Robinson, Salary: 85425.73
After Insertion:
Employee Records:
(1, 'John Doe', 55000.0)
(4, 'Rama', 60000.0)
(3, 'Devi', 50000.0)
(21, 'Kelsey Kline', 33405.27)
(22, 'Janet Watson', 39791.59)
(23, 'Timothy Frederick', 38175.53)
(24, 'Mark Wilson', 71078.9)
(25, 'Courtney Curtis', 37774.85)
(26, 'Anna Fry', 69995.45)
(27, 'Rhonda Phillips', 55199.43)
(28, 'Teresa Sims', 46893.71)
(29, 'Kaitlin Webb DDS', 85124.56)
(30, 'Brian Robinson', 85425.73)
Record updated successfully.
After Update:
Employee Records:
(1, 'John Doe', 55000.0)
(4, 'Rama', 60000.0)
(3, 'Devi', 50000.0)
(21, 'Kelsey Kline', 33405.27)
(22, 'Janet Watson', 39791.59)
(23, 'Timothy Frederick', 38175.53)
(24, 'Mark Wilson', 71078.9)
(25, 'Courtney Curtis', 37774.85)
(26, 'Anna Fry', 69995.45)
(27, 'Rhonda Phillips', 55199.43)
(28, 'Teresa Sims', 46893.71)
(29, 'Kaitlin Webb DDS', 85124.56)
(30, 'Brian Robinson', 85425.73)
Record deleted successfully.
After Deletion:
Employee Records:
(1, 'John Doe', 55000.0)
(4, 'Rama', 60000.0)
(3, 'Devi', 50000.0)
(21, 'Kelsey Kline', 33405.27)
(22, 'Janet Watson', 39791.59)
(23, 'Timothy Frederick', 38175.53)
(24, 'Mark Wilson', 71078.9)
(25, 'Courtney Curtis', 37774.85)
(26, 'Anna Fry', 69995.45)
(27, 'Rhonda Phillips', 55199.43)
(28, 'Teresa Sims', 46893.71)
(29, 'Kaitlin Webb DDS', 85124.56)
(30, 'Brian Robinson', 85425.73)